# Generated by Django 5.1.15 on 2026-04-14 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=300, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de reception"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "icon_svg",
                    models.TextField(
                        help_text="Code SVG de l'icone (ex: <svg ...>...</svg>).",
                        verbose_name="Icone SVG",
                    ),
                ),
                (
                    "icon_css_class",
                    models.CharField(
                        blank=True,
                        help_text="Classe de couleur: topo, visu, urban, dao, geo, calc, io, print",
                        max_length=50,
                        verbose_name="Classe CSS icone",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fonctionnalite",
                "verbose_name_plural": "Fonctionnalites",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "icon_svg",
                    models.TextField(
                        blank=True,
                        help_text="Code SVG inline pour l'icone.",
                        verbose_name="Icone SVG",
                    ),
                ),
                (
                    "icon_bg_color",
                    models.CharField(
                        blank=True,
                        default="rgba(8, 145, 178, 0.12)",
                        max_length=100,
                        verbose_name="Couleur fond icone",
                    ),
                ),
                (
                    "bar_css_class",
                    models.CharField(
                        blank=True,
                        help_text="Classe de couleur pour la barre de progression: topo, sig, dev, web",
                        max_length=50,
                        verbose_name="Classe CSS barre",
                    ),
                ),
                (
                    "percentage",
                    models.PositiveIntegerField(default=0, verbose_name="Pourcentage"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Competence",
                "verbose_name_plural": "Competences",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Libelle")),
                ("value", models.CharField(max_length=50, verbose_name="Valeur")),
                (
                    "data_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Laisser vide si la valeur n'est pas un nombre a animer (ex: '3D', '100%').",
                        null=True,
                        verbose_name="Valeur numerique (pour animation compteur)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistique",
                "verbose_name_plural": "Statistiques",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
            ],
            options={
                "verbose_name": "Tag technique",
                "verbose_name_plural": "Tags techniques",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FeatureTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom du tag")),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="core_app.feature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag de fonctionnalite",
                "verbose_name_plural": "Tags de fonctionnalites",
            },
        ),
        migrations.CreateModel(
            name="SkillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Element")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core_app.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Element de competence",
                "verbose_name_plural": "Elements de competence",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description courte")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "placeholder_logo_svg",
                    models.TextField(
                        blank=True,
                        help_text="SVG a afficher si pas d'image uploadee.",
                        verbose_name="SVG logo placeholder",
                    ),
                ),
                (
                    "placeholder_bg_style",
                    models.CharField(
                        blank=True,
                        default="background: linear-gradient(135deg, var(--teal), var(--teal-dark));",
                        max_length=200,
                        verbose_name="Style fond placeholder",
                    ),
                ),
                (
                    "placeholder_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Texte placeholder"
                    ),
                ),
                (
                    "placeholder_sub",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Sous-texte placeholder",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Lien du projet")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "En ligne"),
                            ("soon", "Bientot disponible"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Projet vedette"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="core_app.tag", verbose_name="Tags"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["order"],
            },
        ),
    ]
