# Generated by Django 5.1.15 on 2026-04-14 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nom complet"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=30, verbose_name="Telephone")),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("geometre", "Geometre topographe"),
                            ("urbaniste", "Urbaniste"),
                            ("geomaticien", "Geomaticien / SIG"),
                            ("ingenieur", "Ingenieur civil / BTP"),
                            ("architecte", "Architecte"),
                            ("etudiant", "Etudiant"),
                            ("enseignant", "Enseignant / Chercheur"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Profession",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Entreprise / Organisation",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Pays")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "heard_from",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("social", "Reseaux sociaux"),
                            ("search", "Moteur de recherche"),
                            ("friend", "Bouche a oreille / Collegue"),
                            ("linkedin", "LinkedIn"),
                            ("whatsapp", "WhatsApp"),
                            ("event", "Evenement / Conference"),
                            ("other", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Comment nous avez-vous connu ?",
                    ),
                ),
                (
                    "intended_use",
                    models.TextField(
                        blank=True,
                        help_text="Dans quel cadre comptez-vous utiliser TOPORAHMA ?",
                        verbose_name="Usage prevu du logiciel",
                    ),
                ),
                (
                    "accepts_newsletter",
                    models.BooleanField(
                        default=True,
                        help_text="Mises a jour, conseils d'utilisation et nouveautes.",
                        verbose_name="Accepte de recevoir des nouvelles",
                    ),
                ),
                (
                    "has_contributed",
                    models.BooleanField(
                        default=False, verbose_name="A contribue financierement"
                    ),
                ),
                (
                    "contribution_amount",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Montant de la contribution (FCFA)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User-Agent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de la demande"
                    ),
                ),
                (
                    "downloaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date du telechargement"
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de telechargement",
                "verbose_name_plural": "Demandes de telechargement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Nom"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                        verbose_name="Note globale (1-5)",
                    ),
                ),
                (
                    "what_liked",
                    models.TextField(blank=True, verbose_name="Ce que vous avez aime"),
                ),
                (
                    "what_to_improve",
                    models.TextField(
                        blank=True, verbose_name="Ce qui peut etre ameliore"
                    ),
                ),
                (
                    "features_wanted",
                    models.TextField(
                        blank=True, verbose_name="Fonctionnalites souhaitees"
                    ),
                ),
                (
                    "would_recommend",
                    models.BooleanField(
                        default=True, verbose_name="Recommanderait a un collegue"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date"),
                ),
                (
                    "download_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="core_app.downloadrequest",
                        verbose_name="Telechargement lie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retour utilisateur",
                "verbose_name_plural": "Retours utilisateurs",
                "ordering": ["-created_at"],
            },
        ),
    ]
